### ISSUE TITLE
My system thinks the resulting .exe file is a virus

### ISSUE THREAD

**Issue by ChemicalXandco** [michaelcukier/pytoexe#5]
I have a [simple GUI application](https://github.com/ChemicalXandco/MCMS-minecraft-mod-switcher), when I use this tool and try to download the .exe file, it does this:
![capture64](https://user-images.githubusercontent.com/32775248/40802014-5621f438-650c-11e8-845b-20a99d5928fd.PNG)
Is it a virus? Why does think that it is a virus? Also, here is a screenshot of windows defender which is what appears to be blocking the file:
![capture65](https://user-images.githubusercontent.com/32775248/40802393-6095913a-650d-11e8-886e-66da492d9ec4.PNG)
Is there any way I can stop it from thinking it is a virus?

**Comment by michaelcukier** [comment]
Yes, my converter uses PyInstaller to perform the conversion, and [is known to generate .exe's flagged as viruses](https://www.google.co.uk/search?q=pyinstaller+virus&rlz=1C5CHFA_enGB763GB763&oq=pyinstaller+virus&aqs=chrome..69i57j0l4j69i64.1907j0j7&sourceid=chrome&ie=UTF-8). There isn't much you can do.

**Comment by michaelcukier** [comment]
Yes, my converter uses PyInstaller to perform the conversion, and [is known to generate .exe's flagged as viruses](https://www.google.co.uk/search?q=pyinstaller+virus&rlz=1C5CHFA_enGB763GB763&oq=pyinstaller+virus&aqs=chrome..69i57j0l4j69i64.1907j0j7&sourceid=chrome&ie=UTF-8). There isn't much you can do.
